name: Deploy Spring Project

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ 저장소 코드 가져오기
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ JDK 17 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          java-package: jdk
          distribution: 'temurin'

      # 3️⃣ Gradle 실행 권한 부여
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      # env 파일 생성
      - name: Create .env file
        run: |
          WORKSPACE=${{ github.workspace }}
          echo "PROD_MYSQL_HOST=${{ secrets.PROD_MYSQL_HOST }}" >> $WORKSPACE/.env
          echo "PROD_MYSQL_DB_NAME=${{ secrets.PROD_MYSQL_DB_NAME }}" >> $WORKSPACE/.env
          echo "PROD_MYSQL_DB_USERNAME=${{ secrets.PROD_MYSQL_DB_USERNAME }}" >> $WORKSPACE/.env
          echo "PROD_MYSQL_DB_PASSWORD=${{ secrets.PROD_MYSQL_DB_PASSWORD }}" >> $WORKSPACE/.env

          echo "PROD_MONGO_DB_USER=${{ secrets.PROD_MONGO_DB_USER }}" >> $WORKSPACE/.env
          echo "PROD_MONGO_DB_PASSWORD=${{ secrets.PROD_MONGO_DB_PASSWORD }}" >> $WORKSPACE/.env
          echo "PROD_MONGO_DB_HOST=${{ secrets.PROD_MONGO_DB_HOST }}" >> $WORKSPACE/.env
          echo "PROD_MONGO_DB_NAME=${{ secrets.PROD_MONGO_DB_NAME }}" >> $WORKSPACE/.env

          echo "PROD_REDIS_HOST=${{ secrets.PROD_REDIS_HOST }}" >> $WORKSPACE/.env
          echo "PROD_REDIS_PORT=${{ secrets.PROD_REDIS_PORT }}" >> $WORKSPACE/.env
          echo "PROD_REDIS_PASSWORD=${{ secrets.PROD_REDIS_PASSWORD }}" >> $WORKSPACE/.env

          echo "PROD_JWT_SECRET=${{ secrets.PROD_JWT_SECRET }}" >> $WORKSPACE/.env

          echo "GOOGLE_EMAIL=${{ secrets.GOOGLE_EMAIL }}" >> $WORKSPACE/.env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> $WORKSPACE/.env

      # 4️⃣ Gradle 빌드 (JAR 생성)
      - name: Build with Gradle
        run: ./gradlew clean build
        env:
          PROD_MYSQL_HOSTNAME: ${{ secrets.PROD_MYSQL_HOSTNAME }}
          PROD_MYSQL_DB_NAME: ${{ secrets.PROD_MYSQL_DB_NAME }}
          PROD_MYSQL_DB_USERNAME: ${{ secrets.PROD_MYSQL_DB_USERNAME }}
          PROD_MYSQL_DB_PASSWORD: ${{ secrets.PROD_MYSQL_DB_PASSWORD }}

          PROD_MONGO_DB_HOST: ${{ secrets.PROD_MONGO_DB_HOST }}
          PROD_MONGO_DB_PASSWORD: ${{ secrets.PROD_MONGO_DB_PASSWORD }}
          PROD_MONGO_DB_NAME: ${{ secrets.PROD_MONGO_DB_NAME }}

          PROD_REDIS_HOST: ${{ secrets.PROD_REDIS_HOST }}
          PROD_REDIS_PORT: ${{ secrets.PROD_REDIS_PORT }}
          PROD_REDIS_PASSWORD: ${{ secrets.PROD_REDIS_PASSWORD }}

          PROD_JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}

          GOOGLE_EMAIL: ${{ secrets.GOOGLE_EMAIL }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          source: ".env,build/libs/*.jar"
          target: "/home/ubuntu/app/"

      # 6️⃣ EC2에서 실행 (기존 프로세스 종료 후 새로운 JAR 실행)
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          timeout: 120s
          script: |
            cd /home/ubuntu/app

            # 기존 프로세스 종료
            PID=$(pgrep -f 'cornchat.jar')
            if [ -z "$PID" ]; then
              echo "No running process found for cornchat.jar"
            else
              echo "Stopping existing process: $PID"
              #git checkisudo kill -9 $PID || echo "Failed to kill process $PID"
            fi
      
            # 최신 JAR 파일 찾기 및 실행
            JAR_FILE=$(ls -t build/libs/*.jar | head -n 1)
            mv $JAR_FILE cornchat.jar
      
            # 환경 변수 적용
            export $(grep -v '^#' /home/ubuntu/app/.env | xargs)
            export SPRING_PROFILES_ACTIVE=prod
      
            nohup java -jar cornchat.jar > /home/ubuntu/app.log 2>&1 &
